# Site settings
title: A Long Way Comes From
email: ace.leo.zhu@gmail.com
description: iOS JS Life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sanshanchuns.github.io" # the base hostname & protocol for your site
twitter_username: sanshanchuns
github_username:  sanshanchuns

# Build settings
markdown: kramdown
